version: "3"
services:
  server:
    build: ./
    # env_file: ./.env
    ports:
      - "${OUT_PORT}:${APP_PORT}"
    networks:
      - dateam-app
    depends_on:
      - postgres
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - dateam-app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/src/db/DBInitSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  dateam-app:
    driver: bridge
volumes:
  postgres-data:
    driver: local
