version: "3"
services:
  server:
    build: ./
    # env_file: ./.env
    ports:
      - "3000:3000"
    networks:
      - dateam-app
    depends_on:
      - postgres
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_DB=dateam
      - POSTGRES_USER=csc302
      - POSTGRES_PASSWORD=1&J7lgO5EnGmEgOPKXh3
    ports:
      - "5431:5432"
    networks:
      - dateam-app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/src/db/DBInitSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  dateam-app:
    driver: bridge
volumes:
  postgres-data:
    driver: local
