version: "3"
services:
  frontend:
    image: frontend
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    environment:
      - PORT=3000
    ports:
      - 3000:3000
  backend:
    image: backend
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    env_file: ./.env
    ports:
      - "${OUT_PORT}:${PORT}"
    networks:
      - dateam-app
    depends_on:
      - postgres
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - dateam-app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/src/db/DBInitSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  dateam-app:
    driver: bridge
volumes:
  postgres-data:
    driver: local
