version: "3"
services:
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/db/DBInitSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres-data:
    driver: local
